---
server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/commands-modul
    username: postgres
    password: 12341234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update